[package]
name = "sortable-js"
version = "0.1.0+js.1.15.0"
edition = "2021"
exclude = ["shell.nix", "nix/*"]

[dependencies]
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3.60", features = ["Element", "HtmlElement"] }
